/**
 * MindMap Incremental Graph Merger
 * Ensures existing nodes and edges are 100% preserved during AI upgrades/expansions.
 * New nodes generated by AI are appended to target parent nodes without destroying existing branches.
 */

export interface MindNode {
  id: string;
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  isRoot?: boolean;
  depth: number;
  collapsed?: boolean;
  emoji?: string;
  color?: string;
  parentId?: string | null;
  details?: string;
  note?: string;
  notes?: string[];
}

export interface MindEdge {
  id: string;
  source: string;
  target: string;
  color?: string;
}

export function mergeIncrementalMindMap(
  existingNodes: MindNode[],
  existingEdges: MindEdge[],
  aiReturnedNodes: any[],
  targetNodeId?: string | null
): { nodes: MindNode[]; edges: MindEdge[] } {
  if (!existingNodes || existingNodes.length === 0) {
    return layoutFreshMindMap(aiReturnedNodes);
  }

  // Deep clone existing nodes & edges to prevent direct state mutation
  const mergedNodes: MindNode[] = JSON.parse(JSON.stringify(existingNodes));
  const mergedEdges: MindEdge[] = JSON.parse(JSON.stringify(existingEdges));

  const existingIdMap = new Map<string, MindNode>();
  const existingTextMap = new Map<string, MindNode>();

  mergedNodes.forEach((n) => {
    if (n.id) existingIdMap.set(String(n.id).trim(), n);
    if (n.text) existingTextMap.set(n.text.trim().toLowerCase(), n);
  });

  const rootNode = mergedNodes.find((n) => n.isRoot || n.depth === 0) || mergedNodes[0];
  const rootId = rootNode ? rootNode.id : 'root_main';
  const rootX = rootNode ? rootNode.x : 600;
  const rootY = rootNode ? rootNode.y : 400;

  // Determine fallback parent node ID (targetNodeId if provided and valid, else rootId)
  const defaultParentId = (targetNodeId && existingIdMap.has(targetNodeId)) ? targetNodeId : rootId;

  const newNodesToAdd: MindNode[] = [];
  const newEdgesToAdd: MindEdge[] = [];

  // Group incoming new AI nodes by target parentId to calculate balanced vertical centering
  const pendingByParent = new Map<string, any[]>();
  aiReturnedNodes.forEach((aiNode) => {
    const rawId = aiNode.id ? String(aiNode.id).trim() : '';
    const cleanText = aiNode.text ? String(aiNode.text).trim().toLowerCase() : '';
    let matchedNode = (rawId && existingIdMap.has(rawId)) ? existingIdMap.get(rawId) : existingTextMap.get(cleanText);
    if (!matchedNode && aiNode.isRoot && rootNode) {
      matchedNode = rootNode;
    }
    if (!matchedNode) {
      let pId = aiNode.parentId ? String(aiNode.parentId).trim() : null;
      if (pId && !existingIdMap.has(pId)) {
        const parentAiNode = aiReturnedNodes.find((other: any) => other.id === pId);
        if (parentAiNode && parentAiNode.text) {
          const matchedParent = existingTextMap.get(parentAiNode.text.trim().toLowerCase());
          if (matchedParent) pId = matchedParent.id;
        }
      }
      if (!pId || !existingIdMap.has(pId)) pId = defaultParentId;
      const arr = pendingByParent.get(pId) || [];
      arr.push(aiNode);
      pendingByParent.set(pId, arr);
    }
  });

  const addedPerParent = new Map<string, number>();

  aiReturnedNodes.forEach((aiNode: any, idx: number) => {
    const rawId = aiNode.id ? String(aiNode.id).trim() : '';
    const cleanText = aiNode.text ? String(aiNode.text).trim().toLowerCase() : '';

    // Match existing node by ID, exact text title, or root flag
    let matchedNode = (rawId && existingIdMap.has(rawId)) ? existingIdMap.get(rawId) : existingTextMap.get(cleanText);
    if (!matchedNode && aiNode.isRoot && rootNode) {
      matchedNode = rootNode;
    }

    if (matchedNode) {
      // Update details, notes, emoji, color without altering existing (x, y) layout coordinates
      if (aiNode.text && aiNode.text.trim()) matchedNode.text = aiNode.text.trim();
      if (aiNode.details) matchedNode.details = aiNode.details;
      if (aiNode.note) matchedNode.note = aiNode.note;
      if (aiNode.emoji && aiNode.emoji !== '🧠') matchedNode.emoji = aiNode.emoji;
      if (aiNode.color && (!matchedNode.color || matchedNode.color === '#00f2fe')) matchedNode.color = aiNode.color;
    } else {
      // Brand NEW node generated by AI!
      let parentId = aiNode.parentId ? String(aiNode.parentId).trim() : null;

      // Match parentId by text if ID does not exist directly in existingIdMap
      if (parentId && !existingIdMap.has(parentId)) {
        const parentAiNode = aiReturnedNodes.find((other: any) => other.id === parentId);
        if (parentAiNode && parentAiNode.text) {
          const matchedParent = existingTextMap.get(parentAiNode.text.trim().toLowerCase());
          if (matchedParent) {
            parentId = matchedParent.id;
          }
        }
      }

      if (!parentId || !existingIdMap.has(parentId)) {
        parentId = defaultParentId;
      }

      const parentNode = existingIdMap.get(parentId) || rootNode;
      const parentX = parentNode ? parentNode.x : rootX;
      const parentY = parentNode ? parentNode.y : rootY;
      const parentDepth = parentNode ? (parentNode.depth || 0) : 0;
      const parentColor = parentNode ? parentNode.color : '#00f2fe';

      const isParentRoot = parentNode && (parentNode.isRoot || parentNode.id === rootId || parentDepth === 0);

      let isLeft = false;
      if (isParentRoot) {
        const leftCount = mergedNodes.filter((n) => n.parentId === rootId && n.x < rootX).length +
                          newNodesToAdd.filter((n) => n.parentId === rootId && n.x < rootX).length;
        const rightCount = mergedNodes.filter((n) => n.parentId === rootId && n.x >= rootX).length +
                           newNodesToAdd.filter((n) => n.parentId === rootId && n.x >= rootX).length;
        isLeft = leftCount < rightCount;
      } else {
        isLeft = parentX < rootX;
      }

      const offsetX = isLeft ? -220 : 220;

      const existingChildrenInGraph = mergedNodes.filter((n) => n.parentId === parentId);
      const totalNewForParent = (pendingByParent.get(parentId) || []).length;
      const childIdx = addedPerParent.get(parentId) || 0;
      addedPerParent.set(parentId, childIdx + 1);

      let newY = parentY;
      if (existingChildrenInGraph.length > 0) {
        const maxY = Math.max(...existingChildrenInGraph.map((c) => c.y));
        const newChildOffset = (newNodesToAdd.filter((n) => n.parentId === parentId).length + 1) * 65;
        newY = maxY + newChildOffset;
      } else {
        // Center new children around parentY
        const spread = (childIdx - (totalNewForParent - 1) / 2) * 65;
        newY = parentY + spread;
      }

      const newId = (rawId && !existingIdMap.has(rawId)) ? rawId : `n_ai_${Date.now()}_${idx}`;

      const newNode: MindNode = {
        ...aiNode,
        id: newId,
        isRoot: false,
        depth: parentDepth + 1,
        parentId: parentId,
        x: parentX + offsetX,
        y: newY,
        width: aiNode.width || 170,
        height: aiNode.height || 54,
        color: aiNode.color || parentColor || '#ff007f',
        emoji: aiNode.emoji || '💡',
        details: aiNode.details || '',
        note: aiNode.note || '',
      };

      newNodesToAdd.push(newNode);
      existingIdMap.set(newId, newNode);

      newEdgesToAdd.push({
        id: `e_${parentId}_${newId}`,
        source: parentId,
        target: newId,
        color: newNode.color,
      });
    }
  });

  mergedNodes.push(...newNodesToAdd);
  mergedEdges.push(...newEdgesToAdd);

  // Filter out any duplicate edges
  const finalEdges: MindEdge[] = [];
  const seenEdgeKeys = new Set<string>();

  mergedEdges.forEach((e) => {
    const key = `${e.source}->${e.target}`;
    if (!seenEdgeKeys.has(key)) {
      seenEdgeKeys.add(key);
      finalEdges.push(e);
    }
  });

  return { nodes: mergedNodes, edges: finalEdges };
}

/**
 * Layout algorithm for fresh mind maps when no existing nodes are present
 */
export function layoutFreshMindMap(rawNodes: any[]): { nodes: MindNode[]; edges: MindEdge[] } {
  if (!Array.isArray(rawNodes) || rawNodes.length === 0) {
    return { nodes: [], edges: [] };
  }

  const nodes: MindNode[] = [];
  const edges: MindEdge[] = [];

  const rawSeenIds = new Set<string>();
  rawNodes.forEach((n: any, idx: number) => {
    let origId = n.id ? String(n.id).trim() : `node_${idx + 1}`;
    let uniqueId = origId;
    let count = 1;
    while (rawSeenIds.has(uniqueId)) {
      uniqueId = `${origId}_${count++}`;
    }
    rawSeenIds.add(uniqueId);
    n.id = uniqueId;
  });

  const rootNode = rawNodes.find((n: any) => n.isRoot || n.depth === 0) || rawNodes[0];
  const rootId = rootNode.id || 'root_main';
  const rootX = 400;
  const rootY = 300;

  nodes.push({
    ...rootNode,
    id: rootId,
    isRoot: true,
    depth: 0,
    parentId: null,
    x: rootNode.x !== undefined ? rootNode.x : rootX,
    y: rootNode.y !== undefined ? rootNode.y : rootY,
    width: rootNode.width || 220,
    height: rootNode.height || 64,
    color: rootNode.color || '#00f2fe',
    emoji: rootNode.emoji || '🧠',
    details: rootNode.details || '',
    note: rootNode.note || '',
  });

  const level1Nodes = rawNodes.filter((n: any) => n !== rootNode && (n.parentId === rootId || n.depth === 1));
  const otherNodes = rawNodes.filter((n: any) => n !== rootNode && !level1Nodes.includes(n));

  const totalL1 = level1Nodes.length || 1;
  const angleStep = (2 * Math.PI) / totalL1;
  const radius1 = 280;

  level1Nodes.forEach((node: any, idx: number) => {
    const angle = idx * angleStep - Math.PI / 2;
    const x = node.x !== undefined ? node.x : Math.round(rootX + radius1 * Math.cos(angle));
    const y = node.y !== undefined ? node.y : Math.round(rootY + radius1 * Math.sin(angle));
    const nodeId = node.id || `node_l1_${idx}`;

    nodes.push({
      ...node,
      id: nodeId,
      isRoot: false,
      depth: 1,
      parentId: rootId,
      x,
      y,
      width: node.width || 180,
      height: node.height || 56,
      color: node.color || '#ff007f',
      emoji: node.emoji || '🚀',
      details: node.details || '',
      note: node.note || '',
    });

    edges.push({
      id: `e_${rootId}_${nodeId}`,
      source: rootId,
      target: nodeId,
      color: node.color || '#ff007f',
    });

    const children = otherNodes.filter((cn: any) => cn.parentId === node.id || cn.parentId === nodeId);
    const totalChild = children.length;
    if (totalChild > 0) {
      const childRadius = 180;
      const spreadAngle = Math.PI / 3;
      const startAngle = angle - spreadAngle / 2;
      const childStep = totalChild > 1 ? spreadAngle / (totalChild - 1) : 0;

      children.forEach((child: any, cIdx: number) => {
        const cAngle = totalChild > 1 ? startAngle + cIdx * childStep : angle;
        const cx = child.x !== undefined ? child.x : Math.round(x + childRadius * Math.cos(cAngle));
        const cy = child.y !== undefined ? child.y : Math.round(y + childRadius * Math.sin(cAngle));
        const childId = child.id || `node_l2_${idx}_${cIdx}`;

        nodes.push({
          ...child,
          id: childId,
          isRoot: false,
          depth: 2,
          parentId: nodeId,
          x: cx,
          y: cy,
          width: child.width || 160,
          height: child.height || 50,
          color: child.color || node.color || '#10b981',
          emoji: child.emoji || '📌',
          details: child.details || '',
          note: child.note || '',
        });

        edges.push({
          id: `e_${nodeId}_${childId}`,
          source: nodeId,
          target: childId,
          color: child.color || node.color || '#10b981',
        });
      });
    }
  });

  // Attach orphan nodes
  const addedIds = new Set(nodes.map((n) => n.id));
  rawNodes.forEach((n: any, idx: number) => {
    if (!addedIds.has(n.id)) {
      const orphanId = n.id || `orphan_${idx}`;
      nodes.push({
        ...n,
        id: orphanId,
        isRoot: false,
        depth: n.depth || 2,
        parentId: n.parentId || rootId,
        x: n.x !== undefined ? n.x : 500,
        y: n.y !== undefined ? n.y : 500,
        width: n.width || 160,
        height: n.height || 50,
        color: n.color || '#8b5cf6',
        emoji: n.emoji || '📌',
      });
      if (n.parentId && addedIds.has(n.parentId)) {
        edges.push({
          id: `e_${n.parentId}_${orphanId}`,
          source: n.parentId,
          target: orphanId,
          color: n.color || '#8b5cf6',
        });
      }
    }
  });

  return { nodes, edges };
}
